Repository metrics-rs/metrics, pull requests merged in 2024-05, with the labels that each got.

#480 Add community exporter for Sentry to readme
  README.md
Labels: E-simple, T-chore

#477 Update lib.rs
  metrics/src/lib.rs
Labels: C-core, E-simple, T-chore, S-awaiting-release

#483 permit trailing commans in describe macros
  metrics/src/macros.rs
Labels: C-macros, E-simple, T-ergonomics
