Repository metrics-rs/metrics, pull requests merged in 2025-04, with the labels that each got.

#572 Bump thiserror to v2
  Cargo.toml
Labels: C-core, E-simple, T-chore

#566 Use `Cargo.lock` file
  .gitignore
  Cargo.lock
  Cargo.toml
Labels: C-core, E-intermediate, T-ergonomics

#565 make key comparison be order-independent
  metrics/src/key.rs
Labels: C-core, E-intermediate, T-enhancement

#574 Support customizing Prometheus pushgateway HTTP method
  metrics-exporter-prometheus/examples/prometheus_push_gateway.rs
  metrics-exporter-prometheus/src/exporter/builder.rs
  metrics-exporter-prometheus/src/exporter/mod.rs
  metrics-exporter-prometheus/src/exporter/push_gateway.rs
Labels: C-exporter, E-simple, T-ergonomics

#576 prometheus: run metrics render in a tokio blocking thread
  metrics-exporter-prometheus/src/exporter/http_listener.rs
  metrics-exporter-prometheus/src/exporter/push_gateway.rs
Labels: C-exporter, T-enhancement
